In [2]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

x, y = make_classification(n_samples=100, n_features=5)
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [3]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((80, 5), (20, 5), (80,), (20,))

In [4]:
import numpy as np
hidden1_weights = np.zeros(1)
hidden2_weights = np.zeros(1)
output_weights = np.zeros(1)
hidden1_bias = 0
hidden2_bias = 0
output_bias = 0

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [5]:
lr = 0.001
for i in range(100):
    if i % 5 == 0:
        lr *= 0.9
    for j in range(0, len(xtrain), 16):
        hidden1_layer = np.dot(xtrain[j : j + 16], hidden1_weights) + hidden1_bias
        hidden1_layer = sigmoid(hidden1_layer)
        hidden1_layer = hidden1_layer.reshape(-1, 1)
        hidden2_layer = np.dot(hidden1_layer, hidden2_weights) + hidden2_bias
        hidden2_layer = sigmoid(hidden2_layer)
        output_layer = np.dot(hidden2_layer, output_weights) + output_bias
        output_layer = sigmoid(output_layer)
        error = ytrain[j : j + 16] - output_layer
        output_delta = error * output_layer * (1 - output_layer)
        hidden2_delta = output_delta * output_weights * hidden2_layer * (1 - hidden2_layer)
        hidden1_delta = hidden2_delta * hidden2_weights * hidden1_layer * (1 - hidden1_layer)
        output_weights += output_delta * hidden2_layer  * lr
        hidden2_weights += hidden2_delta * hidden1_layer * lr
        hidden1_weights += hidden1_delta * xtrain[j : j + 16] * lr
        output_bias += output_delta
        hidden2_bias += hidden2_delta
        hidden1_bias += hidden1_delta
        print(error ** 2)

ValueError: shapes (16,5) and (1,) not aligned: 5 (dim 1) != 1 (dim 0)

In [15]:
output_weights.shape, hidden1_weights.shape, hidden2_weights.shape, output_bias, hidden1_bias, hidden2_bias

((5,),
 (5,),
 (5,),
 0.04770367363624459,
 array([4.43284327e-10, 4.43284327e-10, 4.43284327e-10, 4.43284327e-10,
        4.43284327e-10]),
 array([-0.00336077, -0.00336077, -0.00336077, -0.00336077, -0.00336077]))

In [16]:
def accuracy(y, ypred):
    return np.sum(y == ypred) / len(y)

ypred = []
for i in range(len(xtest)):
    hidden1_layer = np.dot(xtest[i], hidden1_weights) + hidden1_bias
    hidden1_layer = sigmoid(hidden1_layer)
    hidden2_layer = np.dot(hidden1_layer, hidden2_weights) + hidden2_bias
    hidden2_layer = sigmoid(hidden2_layer)
    output_layer = np.dot(hidden2_layer, output_weights) + output_bias
    output_layer = sigmoid(output_layer)
    ypred.append(1 if output_layer > 0.5 else 0)

print(accuracy(ytest, ypred))

0.6


In [18]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)
ypred = model.predict(xtest)
print(accuracy(ytest, ypred))

1.0


In [1]:
import numpy as np

a = [[3, -2], [1, 1]]
np.linalg.inv(a)

array([[ 0.2,  0.4],
       [-0.2,  0.6]])

In [3]:
a = np.array([[8, 1, 4], [-4, 4, 7], [1, 8, -4]])
np.matmul(a, a.T)

array([[81,  0,  0],
       [ 0, 81,  0],
       [ 0,  0, 81]])